services:
  web:
    build: .
    restart: always
    container_name: beacons-api
    ports:
      - "8001:8000"
    volumes:
      - ./app:/code/app
      - ./migrations:/code/migrations
      - ./alembic.ini:/code/alembic.ini
      - ./room_program_data:/code/room_program_data
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.prod
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        python -c 'import time; time.sleep(3)' &&
        alembic upgrade head &&
        python room_program_data/db_room.py &&
        python room_program_data/db_program.py &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000"  # Removed --reload for production

  db:
    image: postgres:15
    restart: always
    container_name: beacons-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env.prod
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: