services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app
      - ./migrations:/code/migrations
      - ./alembic.ini:/code/alembic.ini
      - ./room_program_data:/code/room_program_data
    depends_on:
      - db
    env_file:
      - .env
    command: >
      sh -c "alembic upgrade head &&
             python room_program_data/db_room.py &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

volumes:
  postgres_data:
