"""empty message

Revision ID: 798887e7d229
Revises: 8801d6ecb5f8
Create Date: 2025-04-01 05:32:24.151663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '798887e7d229'
down_revision: Union[str, None] = '8801d6ecb5f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('is_undergrad', sa.Boolean(), nullable=False))
    op.add_column('programs', sa.Column('faculty', sa.String(), nullable=False))
    op.drop_column('programs', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('programs', 'faculty')
    op.drop_column('programs', 'is_undergrad')
    # ### end Alembic commands ###
