"""empty message

Revision ID: 8801d6ecb5f8
Revises: c5d52df44352
Create Date: 2025-03-31 04:09:44.592209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8801d6ecb5f8'
down_revision: Union[str, None] = 'c5d52df44352'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('program_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_program_id'), 'users', ['program_id'], unique=False)
    op.create_foreign_key(None, 'users', 'programs', ['program_id'], ['id'], ondelete='SET NULL')
    op.drop_column('users', 'share_profile')
    op.drop_column('users', 'education_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('education_level', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('share_profile', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_program_id'), table_name='users')
    op.drop_column('users', 'program_id')
    op.drop_table('programs')
    # ### end Alembic commands ###
