"""empty message

Revision ID: c5b82c8f3d69
Revises: 11b3a4539423
Create Date: 2025-02-08 05:57:46.941181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5b82c8f3d69'
down_revision: Union[str, None] = '11b3a4539423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cookies_user_id_fkey', 'cookies', type_='foreignkey')
    op.create_foreign_key(None, 'cookies', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cookies', type_='foreignkey')
    op.create_foreign_key('cookies_user_id_fkey', 'cookies', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
